!define PINGUPILLS [PinguPills]
!define PHONE [Phone]
!define FIREBASE [Firebase]

@startuml

node "User" as USER

node "Mobile Device" as device {
    frame "App (Dart)" as app
    database "Local Database" as localDB
}

node "Google Firebase" as firebase {
    frame "Firebase API" as api
    database "Realtime Database" as firebaseDB
}

USER --> device
device -- firebase: 1..*
app ..> api

@enduml
