!define PINGUPILLS [PinguPills]
!define PHONE [Phone]
!define FIREBASE [Firebase]

@startuml physical_architecture

node "Mobile Device" as device {
    frame "App (Dart)" as app
    database "Local Database \n       (sqlite)" as localDB
}

node "Google Firebase" as firebase {
    frame "Firebase API" as api
    database "Realtime Database \n           (json)" as firebaseDB
}

app .> localDB
api .> firebaseDB
device -- firebase: 1..*
app ..> api

@enduml
