@startuml domain_model

class Medicament {
    - name: String
    - defaultImage: Image
    - customImage: Image
    - quantity: Integer
    - remainingQuantity: Integer
    - expirationDate: Date
    - lowStockThreshold: Integer
}

class Prescription {
    - dosageFrequency: String
    - dosageQuantity: Integer
    - startDate: Date
    - endDate: Date
    - cancelIntake: Boolean
}

note left of Prescription
    endDate needs to be higher than startDate
end note

class Reminder {
    - reminderTime: Time
    - reminderType: Enum
    - remindLater: Boolean
}

note right of Reminder
    reminderType can be expiration reminder, take medication reminder, low stock reminder
end note

class Preferences {
    - theme: Enum
}

note right of Preferences
    theme can be dark mode or light mode
end note

class User {
    - name: String
}

class MedicamentExpirationNotification {
    - notificationDaysBeforeExpiry: Integer
    - expirationStatus: Boolean
}

class MedicamentLowStockNotification {
    - notificationThreshold: Integer
    - lowStockStatus: Boolean
    - outOfStockStatus: Boolean
}

Medicament "1" *-- "1..*" Prescription
Medicament "1" o-- "1" MedicamentExpirationNotification
Medicament "1" o-- "1" MedicamentLowStockNotification
Prescription "1" *-- "0..*" Reminder
User "1" o-- "1" Preferences
User "1" *-- "0..*" Medicament

@enduml