@startuml

package "Users"{
    [User]
}

package "PinguPills App" {
    [User Interface] as UI
    [Reminder] as Reminder
    [Medication Stock] as Stock
    
    database "Local Database" as LocalDB {
    }
}
package "Firebase" {
    database "Realtime database" as FirebaseDB {

    } 
}

User --> UI
UI --> Reminder : Manage Reminders
UI --> Stock : Manage Stock
Reminder --> LocalDB : Read/Write Reminders
Stock --> LocalDB : Read/Write Stock
Stock --> FirebaseDB : Read Medication Information
@enduml
